package de.shop.shop.model;

//import android.arch.persistence.room.Entity;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Bottle {

    //autogenerated)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull(message="Name must be set")
    @NotEmpty(message="Name cannot be empty")
    @Pattern(regexp = "^[A-Za-z0-9äÄöÖüÜß]*$", message = "Name can only contain letters and digits")
    private String name;
    @Pattern(regexp = "(https:\\/\\/).*\\.(?:jpg|gif|png)", message="Must be valid URL to a picture")
    private String bottlePic;
    @Positive(message="Volume must be > 0")
    private double volume;
    private boolean isAlcoholic;
    @PositiveOrZero(message="VolumePercent must be >= 0")
    private double volumePercent;
    @Positive(message="Price must be > 0")
    private int price;
    @NotEmpty(message="Supplier must be set")
    @NotNull(message="Supplier cannot be empty")
    private String supplier;
    @PositiveOrZero(message="in Stock must be >= 0")
    private int inStock;
}
