package de.shop.shop.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Bottle {

    //autogenerated)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    @NotEmpty
    @Pattern(regexp = "[^A-Za-z0-9]", message = "No valid name")
    private String name;
    @Pattern(regexp = "(https:\\\\/\\\\/).*\\\\.(?:jpg|gif|png)\"")
    private String bottlePic;
    @DecimalMin("0.1")
    private double volume;
    private boolean isAlcoholic;
    //   when value > 0.0, than isAlcoholic true)
    private double volumePercent;
    @Min(1)
    private int price;
    @NotEmpty
    @NotNull
    private String supplier;
    @Min(0)
    private int inStock;
}
